apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: agito
  # This is an extra long description
  description: agito
  links:
    - url: https://github.com/jaswanthm/govhack-2021-coolio-agito
      title: GitHub Repo
      icon: github